bpmn_model_parser:

  model_properties:

    participant:
      - name: name
      - name: presence
        required: true
      - name: process_type
        required: true
        extension: true
      - name: process_subtype
        required: true
        extension: true

    process:
      - name: id
      - name: camunda:versionTag
      - name: documentation
      - name: presence
        required: true
      - name: process_type
        required: true
        extension: true
      - name: process_subtype
        required: true
        extension: true

    lane:
      - name: name
      - name: presence
        required: false
      - name: stage
        required: false
        extension: true

    task:
      - name: name
      - name: stage
        required: true
        extension: true
      - name: activity
        required: true
        extension: true

    startEvent:
      - name: process_status
        required: true
        extension: true

    endEvent:
      - name: process_status
        required: true
        extension: true

    sequenceFlow:
      - name: name
      - name: conclusion
        required: true
        extension: true
      - name: process_status
        extension: true
